### ISSUE TITLE
Use OpenShift favicon

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/www.openshift.io#33]
Here's one: https://assets.openshift.net/content/subdomain/favicon32x32.png

**Comment by pmuir** [comment]
I've added the favicon, but unfortunately nowadays a single 32x32 png for the favicon doesn't cut it, due to icons for people saving bookmarks, saving things on phone screens etc. I really need the svg for this, from which we generate 37 different sizes of favicon actually needed - svg is create as it scales really well. @mindreeper2420 @qodfathr can you hunt down the svg for me?

**Comment by mindreeper2420** [comment]
I'll reach out to the brand and visual design teams to get the icons (or the one svg). The .com site appears to just use the png, so I'll check to see if something else is being done.

**Comment by pmuir** [comment]
If you can get me a bigger png, I think imagemagick can scale it down ok, but svg is still best.

**Comment by qodfathr** [comment]
FYI, in https://issues.jboss.org/browse/RHDENG-1231 you can find an SVG. It's a logotype, but you could remove the text and be left behind with just the icon.

**Comment by mindreeper2420** [comment]
@qodfathr I'll grab those and edit them in Illustrator to keep the svg format. I also reached out to see if there is a specific icon to use for saving the site on phone desktops as an app.

**Comment by mindreeper2420** [comment]
Updated favicon to svg in PR https://github.com/openshiftio/www.openshift.io/pull/38
